name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build and Test
      run: |
        docker build . -t test-container
        # Запускаем проверку и тесты одной командой, чтобы видеть подробный лог
        docker run test-container sh -c "python manage.py check && python manage.py test"
