name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build and Test
      run: |
        docker build . -t test-container
        docker run test-container python manage.py check
        docker run test-container python manage.py test
